// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDd3Bcv_A4Mva2SWh8Z3d20H1sbU5VMCJE',
    appId: '1:201373186715:web:b592892726f95b664ee43e',
    messagingSenderId: '201373186715',
    projectId: 'questions-91940',
    authDomain: 'questions-91940.firebaseapp.com',
    storageBucket: 'questions-91940.appspot.com',
    measurementId: 'G-XKTJPQ295X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClFvQMW6bnmcLD3nvQP6YZSjujKWNK0Io',
    appId: '1:201373186715:android:4b7303a3e2da80654ee43e',
    messagingSenderId: '201373186715',
    projectId: 'questions-91940',
    storageBucket: 'questions-91940.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBk_O6p2TUQ0pOEsuLsx6I4XBVx6KbPmkA',
    appId: '1:201373186715:ios:ef29fa23cd4205c44ee43e',
    messagingSenderId: '201373186715',
    projectId: 'questions-91940',
    storageBucket: 'questions-91940.appspot.com',
    iosClientId: '201373186715-uh7h3nbmo6o7msaccsoa3noubkvkdfe2.apps.googleusercontent.com',
    iosBundleId: 'com.example.twentyTwentyQuestions',
  );
}
